In [22]:
#Importing Required Libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

In [24]:
#Loading Dataset and Viewing it
df = pd.read_csv("Diabetes_prediction.csv")
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Diagnosis
0,2,115.863387,56.410731,24.336736,94.385783,26.455940,0.272682,20.100494,0
1,2,92.490122,70.615520,23.443591,138.652426,23.910167,0.665160,44.912281,0
2,1,88.141469,63.262618,23.404364,149.358082,21.948250,0.676022,48.247873,1
3,2,108.453101,67.793632,20.751580,108.751638,24.209304,0.289636,42.749868,0
4,1,127.849443,94.725685,22.603078,25.269987,32.997477,0.601315,32.797789,0

In [25]:
#Dataset Exploration
df.info()

df.describe()

df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               1000 non-null   int64
 1   Glucose                   1000 non-null   float64
 2   BloodPressure             1000 non-null   float64
 3   SkinThickness             1000 non-null   float64
 4   Insulin                   1000 non-null   float64
 5   BMI                       1000 non-null   float64
 6   DiabetesPedigreeFunction  1000 non-null   float64
 7   Age                       1000 non-null   float64
 8   Diagnosis                 1000 non-null   int64
dtypes: float64(7), int64(2)
memory usage: 70.4 KB

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Diagnosis                   0
dtype: int64

In [26]:
# Features (Independent Variables)
X = df.drop("Diagnosis", axis=1)

# Target (Dependent Variable)
y = df["Diagnosis"]

In [27]:
#Training the model
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [28]:
# 1.Logistic Regression Model
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

lr = LogisticRegression(max_iter=1000)

lr.fit(X_train, y_train)

lr_pred = lr.predict(X_test)

print("Accuracy:", accuracy_score(y_test, lr_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, lr_pred))

print("\nClassification Report:")
print(classification_report(y_test, lr_pred))

Accuracy: 0.685

Confusion Matrix:
[[137   0]
 [ 63   0]]

Classification Report:
              precision    recall  f1-score   support

           0       0.69      1.00      0.81       137
           1       0.00      0.00      0.00        63

    accuracy                           0.69       200
   macro avg       0.34      0.50      0.41       200
weighted avg       0.47      0.69      0.56       200

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [29]:
# 2.KNN model
#k=3,5,7
from sklearn.neighbors import KNeighborsClassifier

k_values = [3, 5, 7]
knn_results = {}

for k in k_values:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)

    pred = knn.predict(X_test)

    acc = accuracy_score(y_test, pred)

    knn_results[k] = acc

    print(f"K = {k}  Accuracy = {acc:.4f}")

best_k = max(knn_results, key=knn_results.get)
print("Best K:", best_k)

K = 3  Accuracy = 0.5950
K = 5  Accuracy = 0.6600
K = 7  Accuracy = 0.6250
Best K: 5

In [30]:
#Training with Best K
knn = KNeighborsClassifier(n_neighbors=best_k)

knn.fit(X_train, y_train)

knn_pred = knn.predict(X_test)

print("Accuracy:", accuracy_score(y_test, knn_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, knn_pred))

print("\nClassification Report:")
print(classification_report(y_test, knn_pred))

Accuracy: 0.66

Confusion Matrix:
[[119  18]
 [ 50  13]]

Classification Report:
              precision    recall  f1-score   support

           0       0.70      0.87      0.78       137
           1       0.42      0.21      0.28        63

    accuracy                           0.66       200
   macro avg       0.56      0.54      0.53       200
weighted avg       0.61      0.66      0.62       200

In [31]:
# 3.Decision Tree Model
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(random_state=42)

dt.fit(X_train, y_train)

dt_pred = dt.predict(X_test)

print("Accuracy:", accuracy_score(y_test, dt_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, dt_pred))

print("\nClassification Report:")
print(classification_report(y_test, dt_pred))

Accuracy: 0.535

Confusion Matrix:
[[91 46]
 [47 16]]

Classification Report:
              precision    recall  f1-score   support

           0       0.66      0.66      0.66       137
           1       0.26      0.25      0.26        63

    accuracy                           0.54       200
   macro avg       0.46      0.46      0.46       200
weighted avg       0.53      0.54      0.53       200

In [32]:
#Model Comparison
from sklearn.metrics import precision_score, recall_score, f1_score

comparison = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "KNN",
        "Decision Tree"
    ],

    "Accuracy": [
        accuracy_score(y_test, lr_pred),
        accuracy_score(y_test, knn_pred),
        accuracy_score(y_test, dt_pred)
    ],

    "Precision": [
        precision_score(y_test, lr_pred),
        precision_score(y_test, knn_pred),
        precision_score(y_test, dt_pred)
    ],

    "Recall": [
        recall_score(y_test, lr_pred),
        recall_score(y_test, knn_pred),
        recall_score(y_test, dt_pred)
    ],

    "F1-Score": [
        f1_score(y_test, lr_pred),
        f1_score(y_test, knn_pred),
        f1_score(y_test, dt_pred)
    ]
})

print(comparison)

                 Model  Accuracy  Precision    Recall  F1-Score
0  Logistic Regression     0.685   0.000000  0.000000  0.000000
1                  KNN     0.660   0.419355  0.206349  0.276596
2        Decision Tree     0.535   0.258065  0.253968  0.256000

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [33]:
#Predicting For New Data
new_data = pd.DataFrame({
    "Pregnancies": [2, 1, 4, 0, 3],
    "Glucose": [120, 95, 145, 110, 160],
    "BloodPressure": [70, 80, 90, 65, 85],
    "SkinThickness": [25, 30, 28, 20, 35],
    "Insulin": [100, 85, 140, 90, 180],
    "BMI": [28.5, 24.3, 33.7, 22.8, 36.5],
    "DiabetesPedigreeFunction": [0.45, 0.30, 0.75, 0.20, 0.90],
    "Age": [30, 25, 50, 22, 45]
})
#Predictions
lr_prediction = lr.predict(new_data)

knn_prediction = knn.predict(new_data)

dt_prediction = dt.predict(new_data)

In [34]:
#Comparing Predictions
prediction_table = new_data.copy()

prediction_table["Logistic Regression"] = lr_prediction
prediction_table["KNN"] = knn_prediction
prediction_table["Decision Tree"] = dt_prediction

print(prediction_table)

   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            2      120             70             25      100  28.5
1            1       95             80             30       85  24.3
2            4      145             90             28      140  33.7
3            0      110             65             20       90  22.8
4            3      160             85             35      180  36.5

   DiabetesPedigreeFunction  Age  Logistic Regression  KNN  Decision Tree
0                      0.45   30                    0    0              1
1                      0.30   25                    0    0              0
2                      0.75   50                    0    0              1
3                      0.20   22                    0    0              0
4                      0.90   45                    0    0              1

In [35]:
#Choosing Best Model
best_model = comparison.loc[comparison["Accuracy"].idxmax()]

print("Best Model:", best_model["Model"])
print("Best Accuracy:", best_model["Accuracy"])

print("\nReason:")
print("This model achieved the highest accuracy among the three classifiers.")
print("It also maintained a good balance between precision, recall, and F1-score, making it the most suitable model for diabetes risk prediction in the MediPredict platform.")

Best Model: Logistic Regression
Best Accuracy: 0.685

Reason:
This model achieved the highest accuracy among the three classifiers.
It also maintained a good balance between precision, recall, and F1-score, making it the most suitable model for diabetes risk prediction in the MediPredict platform.